# Generated by Django 4.2 on 2024-02-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('missing', models.BooleanField(default=False)),
                ('foster', models.BooleanField(default=False)),
                ('adoption', models.BooleanField(default=False)),
                ('general', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('images', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
