# Generated by Django 4.2 on 2024-02-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='../Images')),
            ],
        ),
    ]
