# Generated by Django 4.2 on 2024-03-14 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='images',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='timeline_image')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='timeline.timeline')),
            ],
        ),
    ]
