# Generated by Django 3.2 on 2024-04-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_remove_timeline_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
